version: "3.7"

services:

  flask:
    build: ./flask_app
    container_name: flask
    restart: always
    environment:
      - APP_NAME=webhook
    expose:
      - 3031
    volumes:
      - flask_app:/flask_app/fh_webhook/responses

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"

volumes:
  flask_app:
