"""empty message

Revision ID: 0ac8d066eed4
Revises: 85403b492b5b
Create Date: 2021-05-12 08:45:49.871979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0ac8d066eed4"
down_revision = "85403b492b5b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "availability", sa.Column("created_at", sa.DateTime(), nullable=False)
    )
    op.add_column(
        "availability", sa.Column("updated_at", sa.DateTime(), nullable=False)
    )
    op.add_column("booking", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("booking", sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.add_column("company", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("company", sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.add_column("contact", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("contact", sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.add_column(
        "custom_field", sa.Column("created_at", sa.DateTime(), nullable=False)
    )
    op.add_column(
        "custom_field", sa.Column("updated_at", sa.DateTime(), nullable=False)
    )
    op.add_column(
        "custom_field_instances", sa.Column("created_at", sa.DateTime(), nullable=False)
    )
    op.add_column(
        "custom_field_instances", sa.Column("updated_at", sa.DateTime(), nullable=False)
    )
    op.add_column(
        "custom_field_values", sa.Column("created_at", sa.DateTime(), nullable=False)
    )
    op.add_column(
        "custom_field_values", sa.Column("updated_at", sa.DateTime(), nullable=False)
    )
    op.add_column("customer", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("customer", sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.add_column(
        "customer_prototype", sa.Column("created_at", sa.DateTime(), nullable=False)
    )
    op.add_column(
        "customer_prototype", sa.Column("updated_at", sa.DateTime(), nullable=False)
    )
    op.add_column(
        "customer_type", sa.Column("created_at", sa.DateTime(), nullable=False)
    )
    op.add_column(
        "customer_type", sa.Column("updated_at", sa.DateTime(), nullable=False)
    )
    op.add_column(
        "customer_type_rate", sa.Column("created_at", sa.DateTime(), nullable=False)
    )
    op.add_column(
        "customer_type_rate", sa.Column("updated_at", sa.DateTime(), nullable=False)
    )
    op.add_column(
        "effective_cancellation_policy",
        sa.Column("created_at", sa.DateTime(), nullable=False),
    )
    op.add_column(
        "effective_cancellation_policy",
        sa.Column("updated_at", sa.DateTime(), nullable=False),
    )
    op.add_column("item", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("item", sa.Column("updated_at", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("item", "updated_at")
    op.drop_column("item", "created_at")
    op.drop_column("effective_cancellation_policy", "updated_at")
    op.drop_column("effective_cancellation_policy", "created_at")
    op.drop_column("customer_type_rate", "updated_at")
    op.drop_column("customer_type_rate", "created_at")
    op.drop_column("customer_type", "updated_at")
    op.drop_column("customer_type", "created_at")
    op.drop_column("customer_prototype", "updated_at")
    op.drop_column("customer_prototype", "created_at")
    op.drop_column("customer", "updated_at")
    op.drop_column("customer", "created_at")
    op.drop_column("custom_field_values", "updated_at")
    op.drop_column("custom_field_values", "created_at")
    op.drop_column("custom_field_instances", "updated_at")
    op.drop_column("custom_field_instances", "created_at")
    op.drop_column("custom_field", "updated_at")
    op.drop_column("custom_field", "created_at")
    op.drop_column("contact", "updated_at")
    op.drop_column("contact", "created_at")
    op.drop_column("company", "updated_at")
    op.drop_column("company", "created_at")
    op.drop_column("booking", "updated_at")
    op.drop_column("booking", "created_at")
    op.drop_column("availability", "updated_at")
    op.drop_column("availability", "created_at")
    # ### end Alembic commands ###
