"""empty message

Revision ID: 19618c636f12
Revises: 93905e988491
Create Date: 2022-01-16 07:07:37.010062

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "19618c636f12"
down_revision = "93905e988491"
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bike_usage")
    op.drop_constraint("bike_pkey", "bike")
    op.add_column(
        "bike", sa.Column("id", sa.Integer(), autoincrement=True, primary_key=True)
    )
    op.add_column(
        "bike", sa.Column("readable_name", sa.String(length=255), nullable=False)
    )
    op.create_primary_key(
        "pk_bike_id",
        "bike",
        [
            "id",
        ],
    )
    op.create_index(op.f("ix_bike_uuid"), "bike", ["uuid"], unique=True)
    op.create_unique_constraint(None, "bike", ["readable_name"])
    op.create_table(
        "bike_usages",
        sa.Column("bike_id", sa.BigInteger(), nullable=False),
        sa.Column("availability_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["availability_id"],
            ["availability.id"],
        ),
        sa.ForeignKeyConstraint(
            ["bike_id"],
            ["bike.id"],
        ),
        sa.PrimaryKeyConstraint("bike_id", "availability_id"),
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "bike", type_="unique")
    op.drop_index(op.f("ix_bike_uuid"), table_name="bike")
    op.drop_column("bike", "readable_name")
    op.drop_column("bike", "id")
    op.create_table(
        "bike_usage",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("availability_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "bike_uuid", sa.VARCHAR(length=32), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["availability_id"],
            ["availability.id"],
            name="bike_usage_availability_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["bike_uuid"], ["bike.uuid"], name="bike_usage_bike_uuid_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="bike_usage_pkey"),
    )
    op.drop_table("bike_usages")
    ### end Alembic commands ###
