"""empty message

Revision ID: 35c04042fc4c
Revises: 0ac8d066eed4
Create Date: 2021-05-26 19:57:07.710038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "35c04042fc4c"
down_revision = "0ac8d066eed4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "custom_field", "extended_options", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "custom_field", "extended_options", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
