"""empty message

Revision ID: 3da8ac0df2af
Revises: 35c04042fc4c
Create Date: 2021-07-02 20:24:49.076344

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3da8ac0df2af'
down_revision = '35c04042fc4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_field_instance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('custom_field_id', sa.Integer(), nullable=True),
    sa.Column('availability_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['availability_id'], ['availability.id'], ),
    sa.ForeignKeyConstraint(['custom_field_id'], ['custom_field.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custom_field_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=2048), nullable=True),
    sa.Column('display_value', sa.String(length=2048), nullable=True),
    sa.Column('custom_field_id', sa.Integer(), nullable=True),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.ForeignKeyConstraint(['custom_field_id'], ['custom_field.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('custom_field_instances')
    op.drop_table('custom_field_values')
    op.alter_column('availability', 'maximum_party_size',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.alter_column('availability', 'minimum_party_size',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.add_column('booking', sa.Column('receipt_subtotal', sa.Integer(), nullable=True))
    op.drop_column('booking', 'receipt_subtotals')
    op.drop_constraint('contact_booking_id_key', 'contact', type_='unique')
    op.drop_constraint('contact_booking_id_fkey', 'contact', type_='foreignkey')
    op.create_foreign_key(None, 'contact', 'booking', ['id'], ['id'])
    op.drop_column('contact', 'booking_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('booking_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'contact', type_='foreignkey')
    op.create_foreign_key('contact_booking_id_fkey', 'contact', 'booking', ['booking_id'], ['id'])
    op.create_unique_constraint('contact_booking_id_key', 'contact', ['booking_id'])
    op.add_column('booking', sa.Column('receipt_subtotals', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('booking', 'receipt_subtotal')
    op.alter_column('availability', 'minimum_party_size',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.alter_column('availability', 'maximum_party_size',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.create_table('custom_field_values',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('display_value', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('custom_field_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('booking_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], name='custom_field_values_booking_id_fkey'),
    sa.ForeignKeyConstraint(['custom_field_id'], ['custom_field.id'], name='custom_field_values_custom_field_id_fkey'),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name='custom_field_values_customer_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='custom_field_values_pkey')
    )
    op.create_table('custom_field_instances',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('custom_field_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('availability_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['availability_id'], ['availability.id'], name='custom_field_instances_availability_id_fkey'),
    sa.ForeignKeyConstraint(['custom_field_id'], ['custom_field.id'], name='custom_field_instances_custom_field_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='custom_field_instances_pkey')
    )
    op.drop_table('custom_field_value')
    op.drop_table('custom_field_instance')
    # ### end Alembic commands ###
