"""empty message

Revision ID: 93905e988491
Revises: 6c4f84fc263e
Create Date: 2021-12-19 11:36:36.039856

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "93905e988491"
down_revision = "6c4f84fc263e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bike",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("uuid", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "bike_usage",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("availability_id", sa.BigInteger(), nullable=False),
        sa.Column("bike_uuid", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["availability_id"],
            ["availability.id"],
        ),
        sa.ForeignKeyConstraint(
            ["bike_uuid"],
            ["bike.uuid"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bike_usage")
    op.drop_table("bike")
    # ### end Alembic commands ###
