"""empty message

Revision ID: 93bcc34a9d67
Revises: 19618c636f12
Create Date: 2022-07-04 20:23:54.675222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93bcc34a9d67'
down_revision = '19618c636f12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'contact', 'normalized_phone', type_=sa.VARCHAR(length=256), nullable=True)
    op.alter_column('contact', 'phone', type_=sa.VARCHAR(length=256), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contact', 'phone',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('contact', 'normalized_phone',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    # ### end Alembic commands ###
